user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

get_recipe:
    resource: "@GetRecipeBundle/Controller/"
    type:     annotation
    prefix:   /

recipe:
    resource: "@GetRecipeBundle/Resources/config/routing.yml"
    prefix: /
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"