get_recipe:
    resource: "@RecipeBundle/Controller/"
    type:     annotation
    prefix:   /
recipe:
    resource: "@RecipeBundle/Resources/config/routing.yml"
    prefix: /
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
