user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

get_recipe_controller:
    resource: "@GetRecipeBundle/Controller/"
    type:     annotation
    prefix:   /

recipe:
    resource: "@GetRecipeBundle/Resources/config/routing.yml"
    prefix: /
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
#fos_comment_api:
#    type: rest
#    resource: "@FOSCommentBundle/Resources/config/routing.yml"
#    prefix: /api
#    defaults: { _format: html }
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"