# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
     addComponentsAndSetType:
          class: GetRecipeBundle\Form\ComponentsForRecipes
     images_uploader:
        class: UserBundle\FileUploader
        arguments: ["%images_directory%"]
     app.logo_uploader:
        class: UserBundle\FileUploader
        arguments: ["%logo_directory%"]
     acme_user.password_resetting:
        class: UserBundle\EventListener\RegistrationListener
        arguments: ['@router', '@session']
        tags:
        - { name: kernel.event_subscriber }
